/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfigurator: typeof import('./components/layout/app-configurator.vue')['default']
    AppFooter: typeof import('./components/layout/app-footer.vue')['default']
    AppLayout: typeof import('./components/layout/app-layout.vue')['default']
    AppMenu: typeof import('./components/layout/app-menu.vue')['default']
    AppMenuItem: typeof import('./components/layout/app-menu-item.vue')['default']
    AppSidebar: typeof import('./components/layout/app-sidebar.vue')['default']
    AppTopbar: typeof import('./components/layout/app-topbar.vue')['default']
    BasicPlays: typeof import('./views/basic-plays.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EoIcon: typeof import('./components/icons/eo-icon.vue')['default']
    ErrorMessage: typeof import('./components/views/debug/error-message.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JsonViewer: typeof import('./components/views/debug/json-viewer.vue')['default']
    LoadingSpinner: typeof import('./components/views/debug/loading-spinner.vue')['default']
    Login: typeof import('./views/login.vue')['default']
    LogoIcon: typeof import('./components/icons/logo-icon.vue')['default']
    LogoutButton: typeof import('./components/buttons/logout-button.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModelPlay: typeof import('./views/plays/model-play.vue')['default']
    Nucleus: typeof import('./views/nucleus.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RecordPlay: typeof import('./views/plays/record-play.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RpcPlay: typeof import('./views/plays/rpc-play.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ViewPlay: typeof import('./views/plays/view-play.vue')['default']
    Views: typeof import('./views/index.vue')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
