/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/basic-plays': RouteRecordInfo<
      '/basic-plays',
      '/basic-plays',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nucleus': RouteRecordInfo<
      '/nucleus',
      '/nucleus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plays/model-play': RouteRecordInfo<
      '/plays/model-play',
      '/plays/model-play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plays/record-play': RouteRecordInfo<
      '/plays/record-play',
      '/plays/record-play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plays/rpc-play': RouteRecordInfo<
      '/plays/rpc-play',
      '/plays/rpc-play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plays/view-play': RouteRecordInfo<
      '/plays/view-play',
      '/plays/view-play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/basic-plays.vue': {
      routes:
        | '/basic-plays'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/views/nucleus.vue': {
      routes:
        | '/nucleus'
      views:
        | never
    }
    'src/views/plays/model-play.vue': {
      routes:
        | '/plays/model-play'
      views:
        | never
    }
    'src/views/plays/record-play.vue': {
      routes:
        | '/plays/record-play'
      views:
        | never
    }
    'src/views/plays/rpc-play.vue': {
      routes:
        | '/plays/rpc-play'
      views:
        | never
    }
    'src/views/plays/view-play.vue': {
      routes:
        | '/plays/view-play'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
